[package]
name = "client"
version = "0.1.0"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.1"
ot = { git = "https://github.com/pandaman64/ot.git" }
serde = "1.0"
serde_json = "1.0"
failure = "0.1.1"
failure_derive = "0.1.1"
