[package]
name = "server"
version = "0.1.0"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

actix-web = "0.6"

tera = "0.11"

env_logger = "0.5"

sha2 = "0.7.0"

failure = "0.1.1"
failure_derive = "0.1.1"

uuid = { version = "0.6.2", features = ["v4", "serde"] }

lazy_static = "1.0"

tokio-fs = "0.1.4"
tokio-process = "0.2.3"
tokio-timer = "0.2.8"

futures = "0.1"

