[package]
name = "server"
version = "0.1.0"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

rocket = "0.3.6"
rocket_codegen = "0.3.6"
sha2 = "0.7.0"

rocket_cors = "0.2.1"

ot = { git = "https://github.com/pandaman64/ot.git" }

failure = "0.1.1"
failure_derive = "0.1.1"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json", "tera_templates", "uuid"]

