[package]
name = "server"
version = "0.1.0"
authors = ["pandaman64 <kointosudesuyo@infoseek.jp>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"

rocket = "0.3.6"
rocket_codegen = "0.3.6"
sha2 = "0.7.0"

tempfile = "2.2.0"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]

